// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// marsskem
List marsskem(List& MLEobj);
RcppExport SEXP _MARSS_marsskem(SEXP MLEobjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type MLEobj(MLEobjSEXP);
    rcpp_result_gen = Rcpp::wrap(marsskem(MLEobj));
    return rcpp_result_gen;
END_RCPP
}
// marsskf
List marsskf(List& MLEobj);
RcppExport SEXP _MARSS_marsskf(SEXP MLEobjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type MLEobj(MLEobjSEXP);
    rcpp_result_gen = Rcpp::wrap(marsskf(MLEobj));
    return rcpp_result_gen;
END_RCPP
}
// marsskfss
List marsskfss(List& MLEobj);
RcppExport SEXP _MARSS_marsskfss(SEXP MLEobjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type MLEobj(MLEobjSEXP);
    rcpp_result_gen = Rcpp::wrap(marsskfss(MLEobj));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MARSS_marsskem", (DL_FUNC) &_MARSS_marsskem, 1},
    {"_MARSS_marsskf", (DL_FUNC) &_MARSS_marsskf, 1},
    {"_MARSS_marsskfss", (DL_FUNC) &_MARSS_marsskfss, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_MARSS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
