# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

marsskem <- function(MLEobj) {
    .Call('_MARSS_marsskem', PACKAGE = 'MARSS', MLEobj)
}

marsskf <- function(MLEobj) {
    .Call('_MARSS_marsskf', PACKAGE = 'MARSS', MLEobj)
}

marsskfss <- function(MLEobj) {
    .Call('_MARSS_marsskfss', PACKAGE = 'MARSS', MLEobj)
}

