# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenAB <- function(AA, BB) {
    .Call('_MARSS_eigenAB', PACKAGE = 'MARSS', AA, BB)
}

eigenMapAB <- function(A, B) {
    .Call('_MARSS_eigenMapAB', PACKAGE = 'MARSS', A, B)
}

eigenAtB <- function(AA, BB) {
    .Call('_MARSS_eigenAtB', PACKAGE = 'MARSS', AA, BB)
}

eigenMapAtB <- function(A, B) {
    .Call('_MARSS_eigenMapAtB', PACKAGE = 'MARSS', A, B)
}

eigenAb <- function(AA, bb) {
    .Call('_MARSS_eigenAb', PACKAGE = 'MARSS', AA, bb)
}

eigenMapAb <- function(A, b) {
    .Call('_MARSS_eigenMapAb', PACKAGE = 'MARSS', A, b)
}

eigenaBa <- function(aa, BB) {
    .Call('_MARSS_eigenaBa', PACKAGE = 'MARSS', aa, BB)
}

eigenMapaBa <- function(a, B) {
    .Call('_MARSS_eigenMapaBa', PACKAGE = 'MARSS', a, B)
}

eigentAB <- function(AA, BB) {
    .Call('_MARSS_eigentAB', PACKAGE = 'MARSS', AA, BB)
}

eigenMaptAB <- function(A, B) {
    .Call('_MARSS_eigenMaptAB', PACKAGE = 'MARSS', A, B)
}

eigenAtBC <- function(AA, BB, CC) {
    .Call('_MARSS_eigenAtBC', PACKAGE = 'MARSS', AA, BB, CC)
}

eigenMapAtBC <- function(A, B, C) {
    .Call('_MARSS_eigenMapAtBC', PACKAGE = 'MARSS', A, B, C)
}

eigenABC <- function(AA, BB, CC) {
    .Call('_MARSS_eigenABC', PACKAGE = 'MARSS', AA, BB, CC)
}

eigenMapABC <- function(A, B, C) {
    .Call('_MARSS_eigenMapABC', PACKAGE = 'MARSS', A, B, C)
}

eigenABtA <- function(AA, BB) {
    .Call('_MARSS_eigenABtA', PACKAGE = 'MARSS', AA, BB)
}

eigenABtAA <- function(AA, BB) {
    .Call('_MARSS_eigenABtAA', PACKAGE = 'MARSS', AA, BB)
}

eigenABtC <- function(AA, BB, CC) {
    .Call('_MARSS_eigenABtC', PACKAGE = 'MARSS', AA, BB, CC)
}

eigenMapABtC <- function(A, B, C) {
    .Call('_MARSS_eigenMapABtC', PACKAGE = 'MARSS', A, B, C)
}

eigenSymm <- function(AA) {
    .Call('_MARSS_eigenSymm', PACKAGE = 'MARSS', AA)
}

eigenMapSymm <- function(A) {
    .Call('_MARSS_eigenMapSymm', PACKAGE = 'MARSS', A)
}

getDeterminant <- function(AA) {
    .Call('_MARSS_getDeterminant', PACKAGE = 'MARSS', AA)
}

getMapDeterminant <- function(A) {
    .Call('_MARSS_getMapDeterminant', PACKAGE = 'MARSS', A)
}

dMat <- function(aa, r, c) {
    .Call('_MARSS_dMat', PACKAGE = 'MARSS', aa, r, c)
}

